Product card
Derecky/study_coffee pull request #24
Opened 2022-09-19 23:16 UTC by Hime-chan

Criei o card de produto e a funcionalidade de colocar no carrinho.
As alteranções no carrinho podem ser vistas no Header (sem detalhes, só temporariamente).
O design do card pode ser visto na página principal (também sem detalhes e temporariamente).

Se/quando tiver tudo certo, vou apagar os conteúdos temporários antes de passar para a main.

- Dúvida: Como coloquei o estado "currentCart" na página index.tsx (já que ele será usado em todas as páginas do site), defini a função que o altera lá também. Fiz certo?

2022-09-20 19:56 UTC, Derecky requested changes

2022-09-20 19:56 UTC, Derecky commented on src/components/MainPage/styles.ts
> +    border:1px solid blue;
remover a borda que era pra visualização

2022-09-20 19:56 UTC, Derecky commented on src/components/Product/Product.tsx
> +        return (<ProductCardContainer
Há uma prática de programação que você só faz o necessário quando necessário, pensar muito a frente acabamos adicionando código que nunca usamos, é esse caso de mudar a cor da label que é única em todos os cards ou a cor do card, etc...


Pra estudo, como é nosso projeto, ainda vale, mas numa empresa mesmo, não é tão válido isso

2022-09-21 20:31 UTC, xnd-dev approved these changes
lgtm

2022-09-22 01:11 UTC, Derecky approved these changes

2022-09-22 16:56 UTC, merged